- hosts: host01
  tasks:
    - name: "copy website"
      copy:
        src: site/
        dest: /var/www/default

- hosts: host02
  tasks:
    - name: "copy website"
      copy:
        src: site/
        dest: /var/www/default
    - name: "edit website"
      become: yes
      become_user: root
      replace:
        path: /var/www/default/index.html
        regexp: "Host1"
        replace: "Host2"

- hosts: host03
  tasks:
    - name: "copy website"
      copy:
        src: site/
        dest: /var/www/default
    - name: "edit website"
      become: yes
      become_user: root
      replace:
        path: /var/www/default/index.html
        regexp: "Host1"
        replace: "Host3"
